# Generated by Django 3.2.2 on 2022-11-07 08:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('body', models.TextField(verbose_name='Matn')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Rasm')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Video')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=25, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism sharif')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='full_name')),
                ('age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('body', models.TextField(verbose_name='Matn')),
                ('read', models.BooleanField(default=False, verbose_name="O'qildi")),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-read', '-created_at'),
            },
        ),
    ]
