# Generated by Django 4.1.2 on 2023-02-09 02:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Categoriya nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Kategoriya haqida')),
                ('category_form', models.BooleanField(blank=True, default=False, null=True, verbose_name="Kategoriyada formula bor/yo'q")),
                ('ball35', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Formulaga qo'shiladigan ball")),
                ('tur', models.CharField(blank=True, choices=[('xavotir', 'Xavotir HADS'), ('depressiya', 'Depressiya HADS'), ('boshqa', 'Boshqa'), ('yoq', "Yo'q")], default='yoq', max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mytest.category', verbose_name='Yuqori kategoriya')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Formula nomi: E1/E2...')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Test matni')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category', unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='mytest.category', verbose_name='Kategoriya')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_form', to='mytest.form', verbose_name='Form')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Test_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Test varianti')),
                ('ball', models.PositiveIntegerField(verbose_name='Variant ostidagi ball')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='mytest.test', verbose_name='Test')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism Familya')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='full_name', unique=True)),
                ('age', models.PositiveIntegerField(verbose_name='Yoshi')),
                ('gender', models.CharField(choices=[('man', 'Erkak'), ('woman', 'Ayol')], default='man', max_length=50, verbose_name='Jinsi')),
                ('test_ball', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Testning yakuniy balli')),
                ('test_result', models.CharField(blank=True, max_length=25, null=True, verbose_name='Tashxis')),
                ('test_api', models.JSONField(blank=True, default={}, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_category', to='mytest.category', verbose_name='Kategoriya')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
