# Generated by Django 4.1.2 on 2022-11-19 07:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Categoriya nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('body', models.TextField(verbose_name='Kategoriya haqida')),
                ('category_form', models.BooleanField(default=False, verbose_name="Kategoriyada formula bor/yo'q")),
                ('ball35', models.PositiveIntegerField(verbose_name="Formulaga qo'shiladigan ball")),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Formula nomi: E1/E2...')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='full_name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism Familya')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='full_name')),
                ('age', models.PositiveIntegerField(verbose_name='Yoshi')),
                ('gender', models.CharField(choices=[('man', 'Erkak'), ('woman', 'Ayol')], default='man', max_length=50, verbose_name='Jinsi')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_category', to='mytest.category', verbose_name='Kategoriya')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Form_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Formula soni')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('delete', 'Delete')], default='active', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytest.category', verbose_name='Kategoriya nomi')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytest.form', verbose_name='Formula')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
