# Generated by Django 4.1.2 on 2022-11-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ball35',
            field=models.PositiveIntegerField(blank=True, verbose_name="Formulaga qo'shiladigan ball"),
        ),
        migrations.AlterField(
            model_name='category',
            name='body',
            field=models.TextField(blank=True, verbose_name='Kategoriya haqida'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_form',
            field=models.BooleanField(blank=True, default=False, verbose_name="Kategoriyada formula bor/yo'q"),
        ),
    ]
