# Generated by Django 3.1 on 2023-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_auto_20230104_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='test_api',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='test_ball',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Testning yakuniy balli'),
        ),
        migrations.AddField(
            model_name='info',
            name='test_result',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Tashxis'),
        ),
    ]
