# Generated by Django 4.1.2 on 2022-11-19 08:49

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_alter_category_ball35_alter_category_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mytest.category', verbose_name='Yuqori kategoriya'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
