# Generated by Django 3.1 on 2023-01-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0004_auto_20230121_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='test_api',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
