# Generated by Django 4.1.2 on 2022-11-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0004_category_parent_alter_form_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Categoriya nomi'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Formula nomi: E1/E2...'),
        ),
    ]
