# Generated by Django 3.1 on 2023-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0006_auto_20230121_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='test_ball',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Testning yakuniy balli'),
        ),
        migrations.AlterField(
            model_name='info',
            name='test_result',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Tashxis'),
        ),
    ]
