# Generated by Django 3.1 on 2023-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0007_auto_20230121_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='test_result',
            field=models.CharField(blank=True, default=' ', max_length=25, null=True, verbose_name='Tashxis'),
        ),
    ]
