# Generated by Django 3.1 on 2023-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0008_auto_20230121_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='test_ball',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Testning yakuniy balli'),
        ),
    ]
