# Generated by Django 3.1 on 2023-01-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0011_auto_20230121_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='test_result',
            field=models.CharField(blank=True, choices=[('bad', 'Sizning holatingiz yomon'), ('normal', 'Sizning holatingiz yaxshi'), ('well', "Sizning holatingiz a'lo")], default='normal', max_length=25, null=True, verbose_name='Tashxis'),
        ),
    ]
